Release 2.0.0 (9th Jul 2019) 	License update: KVS SDK and GStreamer kvssink plugin are under Apache 2.0 license now. 	C-Producer - New feature 		Language level is C89. It should work for all GCC versions, tested minimum GCC version is 4.1. 		The Kinesis Video Streams C producer library wraps kinesis-video-pic (Platform Independent Code) with additional layer of API that allows scenario and platform-specific callbacks and events. 		Callbacks for sample retry logic implementation are now supported through C Producer 	CPP Producer - Updates 		Language level is C++11 instead of C++14. Required minimum GCC version is 4.8. 		Kinesis Video Producer CPP (kinesis-video-producer directory) is now revised to a wrapper of C Producer SDK which interfaces with the Platform Independent Repository (PIC, kinesis-video-pic directory). 		Platform Independent Code - New functionality 		Automatic CPD (codec private data) extraction from the stream 		Reset stream and reset connection functionality in PIC - In case of unrecoverable errors users can simply call reset stream; internally SDK will free & create the stream. 		Log level supported in PIC. It can be set in member variable of DeviceInfo.ClientInfo. 	Platform Independent Code - Bug Fixes 		Skip over error fragments - SDK will continue skip any invalid fragments are ingested through SDK earlier and continue streaming with valid ingested fragments. It will not just loop back and keep resending the broken fragment now. 		All unit tests (pic_test, cproducer_test, producer_test) are at C++11 level. Required minimum GCC version is 4.8.
	Please note the following changes if you have customized the SDK for your integration and not using samples directly.

		Changes to utility functions:
		RotatingStaticCredentialProvider is removed from C++ producer. Customer can use StaticCredentialProvider instead.
		CredentialProviderUtil and SerializedCredentials are removed from C++ producer.
		Following functions are removed from DefaultCallbackProvider: sleepUntilWithTimeCallback, shutdownStream, notifyResult, getControlPlaneUri, safeFreeBuffer, getStreamStatusFromString.
	Changes to the object model:
		Following attributes have been added: Version number is added to TrackInfo, Frame, StreamDescription, DeviceInfo, StreamInfo.
		Following attributes have been removed: certPath is removed from DeviceInfo in PIC.

diff --git a/kinesis-video-native-build/min-install-script b/kinesis-video-native-build/min-install-script
--- a/kinesis-video-native-build/min-install-script
+++ b/kinesis-video-native-build/min-install-script
@@ -1,5 +1,7 @@
 #!/bin/bash
 
+set -e
+
 # KINESIS_VIDEO_ROOT should point to kinesis-video-native-build directory
 if [ -z $KINESIS_VIDEO_ROOT ]; then
   KINESIS_VIDEO_ROOT=`pwd`
@@ -12,13 +14,14 @@ fi
 
 source $KINESIS_VIDEO_ROOT/install-script-common.sh
 
-set -e
-
 # --------- process args -----------------------------------------------------
 max_parallel=2
 build_type=Release
 build_test=FALSE
 build_gst_artifact=TRUE
+build_jni_only=FALSE
+build_producer=TRUE
+env_var=""
 parse_args $@
 
 setup
@@ -45,21 +48,40 @@ if [[ "$unamestr" == 'Linux' ]]; then
    echo "* liblog4cplus-dev"
 
 elif [[ "$unamestr" =~ ^MINGW ]]; then
-   PLATFORM='mingw'
-   if [[ ! -d ${MINGW_PREFIX}/lib/gstreamer-1.0 ]]; then
-      echo "Installing dependencies"
-      pacman -S --needed --noconfirm base-devel mingw-w64-i686-toolchain mingw-w64-x86_64-toolchain \
-                    git \
-                    mingw-w64-i686-cmake mingw-w64-x86_64-cmake \
-                    mingw-w64-i686-gstreamer mingw-w64-x86_64-gstreamer \
-                    mingw-w64-i686-gst-libav mingw-w64-x86_64-gst-libav \
-                    mingw-w64-i686-gst-plugins-bad mingw-w64-x86_64-gst-plugins-bad \
-                    mingw-w64-i686-gst-plugins-base mingw-w64-x86_64-gst-plugins-base \
-                    mingw-w64-i686-gst-plugins-good mingw-w64-x86_64-gst-plugins-good \
-                    mingw-w64-i686-gst-plugins-ugly mingw-w64-x86_64-gst-plugins-ugly \
-                    mingw-w64-i686-gtest mingw-w64-x86_64-gtest \
-                    mingw-w64-i686-curl mingw-w64-x86_64-curl
-   fi
+    PLATFORM='mingw'
+
+    if [[ "$unamestr" =~ ^MINGW64 ]]; then
+      if [[ ! -d ${MINGW_PREFIX}/lib/gstreamer-1.0 ]]; then
+        echo "Installing dependencies"
+        pacman -S --needed --noconfirm base-devel git
+        pacman -S --needed --noconfirm mingw-w64-x86_64-toolchain \
+                      mingw-w64-x86_64-cmake \
+                      mingw-w64-x86_64-gstreamer \
+                      mingw-w64-x86_64-gst-libav \
+                      mingw-w64-x86_64-gst-plugins-bad \
+                      mingw-w64-x86_64-gst-plugins-base \
+                      mingw-w64-x86_64-gst-plugins-good \
+                      mingw-w64-x86_64-gst-plugins-ugly \
+                      mingw-w64-x86_64-gtest \
+                      mingw-w64-x86_64-curl
+      fi
+
+    elif [[ "$unamestr" =~ ^MINGW32 ]]; then
+      if [[ ! -d ${MINGW_PREFIX}/lib/gstreamer-1.0 ]]; then
+        echo "Installing dependencies"
+        pacman -S --needed --noconfirm base-devel git
+        pacman -S --needed --noconfirm mingw-w64-i686-toolchain \
+                      mingw-w64-i686-cmake \
+                      mingw-w64-i686-gstreamer \
+                      mingw-w64-i686-gst-libav \
+                      mingw-w64-i686-gst-plugins-bad \
+                      mingw-w64-i686-gst-plugins-base \
+                      mingw-w64-i686-gst-plugins-good \
+                      mingw-w64-i686-gst-plugins-ugly \
+                      mingw-w64-i686-gtest \
+                      mingw-w64-i686-curl
+      fi
+    fi
 
 elif [[ "$unamestr" == 'Darwin' ]]; then
    PLATFORM='mac'
@@ -79,7 +101,9 @@ else
 fi
 
 # --------- build + install libs ----------------------------------------------
-if [[ "$PLATFORM" == 'mingw' ]]; then
+
+# log4cplus
+if [[ "$PLATFORM" == 'mingw' ]] && [[ $build_producer == TRUE ]]; then
   # mingw doesnt have prebuilt log4cplus
   echo "Checking log4cplus at ${MINGW_PREFIX}/lib/liblog4cplus.dll.a"
   if [ ! -f ${MINGW_PREFIX}/lib/liblog4cplus.dll.a ]; then
@@ -100,40 +124,95 @@ if [[ "$PLATFORM" == 'mingw' ]]; then
     make
     make install
   fi
+fi
 
-else
-
-  # mingw has prebuilt gtest
+if [[ $build_test == TRUE ]]; then
   echo "Checking googletest at $DOWNLOADS"
-  if [ ! -d $DOWNLOADS/googletest-release-1.8.0 ]; then
-    echo "gtest lib not found. Installing"
-    if [ ! -f $DOWNLOADS/google-test-1.8.0.gz ]; then
-      cd $DOWNLOADS
-      $SYS_CURL -L "https://github.com/google/googletest/archive/release-1.8.0.tar.gz" -o "google-test-1.8.0.gz"
+  # mingw has prebuilt gtest
+  if [[ "$PLATFORM" != 'mingw' ]]; then
+    if [ ! -f $DOWNLOADS/local/lib/libgtest.* ]; then
+      echo "gtest lib not found. Installing"
+      if [ ! -d $DOWNLOADS/googletest-release-1.8.0 ]; then
+        cd $DOWNLOADS
+        $SYS_CURL -L "https://github.com/google/googletest/archive/release-1.8.0.tar.gz" -o "google-test-1.8.0.gz"
+        tar -xvf google-test-1.8.0.gz
+      fi
+      cd $DOWNLOADS/googletest-release-1.8.0
+      cmake -DCMAKE_INSTALL_PREFIX=$DOWNLOADS/local .
+      make -j $max_parallel && make install
     fi
-    cd $DOWNLOADS
-    tar -xvf google-test-1.8.0.gz
+    env_var="$env_var KVS_GTEST_ROOT=$DOWNLOADS/local"
   fi
 fi
 
-if [ -d $DOWNLOADS/local ]; then
+#------------ jsmn ------------------------------------------------------------------------------------------------
+
+if [[ $build_producer == TRUE ]]; then
+  if [ ! -f $DOWNLOADS/local/lib/libjsmn.* ]; then
+    echo "jsmn lib not found. Installing"
+    if [ ! -f $DOWNLOADS/jsmn.tar.gz ]; then
+      cd $DOWNLOADS
+      $SYS_CURL -L "https://github.com/zserge/jsmn/archive/v1.0.0.tar.gz" -o "jsmn.tar.gz"
+    fi
+    cd $DOWNLOADS
+    tar -xvf jsmn.tar.gz
+    cd $DOWNLOADS/jsmn-1.0.0
+    make clean && make CFLAGS="-fPIC" -j $max_parallel
+    if [ ! -d "$DOWNLOADS/local/lib" ]; then
+      mkdir "$DOWNLOADS/local/lib"
+    fi
+    if [ ! -d "$DOWNLOADS/local/include" ]; then
+      mkdir "$DOWNLOADS/local/include"
+    fi
+    cp libjsmn.a $DOWNLOADS/local/lib
+    cp jsmn.h $DOWNLOADS/local/include
+  fi
+fi
+
+
+if [ -d $DOWNLOADS/local/lib/gstreamer-1.0 ] && [ $build_gst_artifact == TRUE ]; then
   echo "Please remove $DOWNLOADS/local or the Gstreamer there may conflict with system Gstreamer."
   exit 0
+fi
+
+#------------ jsmn ------------------------------------------------------------------------------------------------
+
+echo "Checking jsmn at $DOWNLOADS/local/lib/libjsmn.a"
+if [ ! -f $DOWNLOADS/local/lib/libjsmn.a ]; then
+  echo "jsmn lib not found. Installing"
+  if [ ! -f $DOWNLOADS/jsmn.zip ]; then
+    cd $DOWNLOADS
+    $SYS_CURL -L "https://github.com/zserge/jsmn/archive/v1.0.0.zip" -o "jsmn.zip"
+  fi
+  cd $DOWNLOADS
+  unzip -oq jsmn.zip -d jsmn
+  cd $DOWNLOADS/jsmn/jsmn-1.0.0
+  make CFLAGS="-fPIC" -j $max_parallel
+  rsync libjsmn.a $DOWNLOADS/local/lib/
+  rsync jsmn.h $DOWNLOADS/local/include/
 fi
 
 ## --------- build kinesis video ----------------------------------------------
 cd $KINESIS_VIDEO_ROOT
 clean_up
+
+if [[ ! -z $env_var ]]; then
+  export $env_var
+fi
+
 if [[ "$PLATFORM" == 'mingw' ]]; then
   cmake -G "MSYS Makefiles" -DCMAKE_BUILD_TYPE=${build_type} -DUSE_SYS_LIBRARIES=TRUE \
-  -DBUILD_TEST=${build_test} -DBUILD_GST_ARTIFACT=${build_gst_artifact} CMakeLists.txt
+  -DBUILD_TEST=${build_test} -DBUILD_GST_ARTIFACT=${build_gst_artifact} -DBUILD_PRODUCER=${build_producer} \
+  -DBUILD_JNI=${build_jni_only} \
+  .
 else
   cmake -DCMAKE_BUILD_TYPE=${build_type} -DUSE_SYS_LIBRARIES=TRUE \
-  -DBUILD_TEST=${build_test} -DBUILD_GST_ARTIFACT=${build_gst_artifact} CMakeLists.txt
+  -DBUILD_TEST=${build_test} -DBUILD_GST_ARTIFACT=${build_gst_artifact} -DBUILD_PRODUCER=${build_producer} \
+  -DBUILD_JNI=${build_jni_only} \
+  .
 fi
 
 make -j ${max_parallel}
-
 
 echo "**********************************************************"
 echo Success!!!
